# Generated by Django 3.0.5 on 2021-04-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('price', models.BigIntegerField()),
                ('genre', models.CharField(max_length=1000)),
                ('pages', models.BigIntegerField()),
                ('paperType', models.CharField(max_length=1000)),
                ('rating', models.FloatField()),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
    ]
