# Generated by Django 3.0.5 on 2021-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('FlatNo', models.IntegerField()),
                ('Floor', models.IntegerField()),
                ('StreetName', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=100)),
                ('AreaCode', models.BigIntegerField()),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Landmark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksId', models.IntegerField(default=1234)),
                ('userId', models.IntegerField(default=1234)),
            ],

        ),
        migrations.CreateModel(
            name='Ordered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='surname',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='abc@123.com', max_length=254),
        ),
    ]
