# Generated by Django 3.2 on 2021-04-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_wishlist'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='cart',
        #     name='booksId',
        #     field=models.IntegerField(default=1234),
        # ),
        # migrations.AddField(
        #     model_name='cart',
        #     name='userId',
        #     field=models.IntegerField(default=1234),
        # ),
    ]
